#!/bin/bash
# This is a simple script and will be executed on your CI system if 
# available.  Otherwise it will execute while your application is stopped
# before the build step.  This script gets executed directly, so it
# could be python, php, ruby, etc.

if [ ! -d $OPENSHIFT_DATA_DIR/bin ]; then
  if [ ! -f $OPENSHIFT_DATA_DIR/bin/python ]; then
    # install python 2.7.6
    cd $OPENSHIFT_TMP_DIR
    wget http://python.org/ftp/python/2.7.6/Python-2.7.6.tgz
    tar zxf Python-2.7.6.tgz
    cd Python-2.7.6
    ./configure --prefix=$OPENSHIFT_DATA_DIR
    make install
  fi

  # chdir to /tmp
  cd $OPENSHIFT_TMP_DIR
  # install setuptools
  wget https://bitbucket.org/pypa/setuptools/raw/bootstrap/ez_setup.py -O - | $OPENSHIFT_DATA_DIR/bin/python
  # install pip
  $OPENSHIFT_DATA_DIR/bin/easy_install pip
  # cleanup
  rm -rf $OPENSHIFT_TMP_DIR/*
fi

